### ISSUE TITLE
restarting docker service reports `ulimit: invalid option -- 'p'`

### ISSUE THREAD

**Issue by sebthom** [kaosagnt/toolbox2docker#12]
I don't know what the consequences of this may be, so I just report it.

```
> docker-machine ssh
                        ##         .
                  ## ## ##        ==
               ## ## ## ## ##    ===
           /"""""""""""""""""\___/ ===
      ~~~ {~~ ~~~~ ~~~ ~~~~ ~~~ ~ /  ===- ~~~
           \______ o           __/
             \    \         __/
              \____\_______/
 _                 _   ____     _            _
| |__   ___   ___ | |_|___ \ __| | ___   ___| | _____ _ __
| '_ \ / _ \ / _ \| __| __) / _` |/ _ \ / __| |/ / _ \ '__|
| |_) | (_) | (_) | |_ / __/ (_| | (_) | (__|   <  __/ |
|_.__/ \___/ \___/ \__|_____\__,_|\___/ \___|_|\_\___|_|
docker@default:~$ sudo /etc/init.d/docker restart
Stopping dockerd (3401)
ulimit: invalid option -- 'p'
Starting dockerd
```

**Comment by kaosagnt** [comment]
Busybox provides the shell that this script is executed under and its ulimit command appears to not support the -p option. As this has been the case since Docker Toolbox was born, not being able to set the number of process limit to unlimited has not shown issues. I have commented out this line in the docker init script so the error message goes away. The fix will be in the next release.

**Comment by kaosagnt** [comment]
25.0.2 has been release and this issue fixed so closing. Thanks for the report.
